Update build.properties
SecurityManager has been removed in Java 18, using old version of sbt leads to this exception:
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release